# typed: false
# frozen_string_literal: true

# Code generated by cmd/update-homebrew-formula. DO NOT EDIT.

# Tasks installs the tasks command-line binary.
class Tasks < Formula
  desc "PostgreSQL-backed task management with CLI, web, and MCP interfaces"
  homepage "https://github.com/zachlatta/tasks"
  version "0.0.0.32"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/zachlatta/tasks/releases/download/edge/tasks_edge-SNAPSHOT-c09857c_darwin_arm64.tar.gz"
      sha256 "747b93b8b743e7e932a8f0e2cc34a1ab0ba0fb5b3d58e8f8adbc39c121a3803c"
    else
      url "https://github.com/zachlatta/tasks/releases/download/edge/tasks_edge-SNAPSHOT-c09857c_darwin_amd64.tar.gz"
      sha256 "ff02e878e3083f5ac6c74e0dcfce8ac78a3eeeb5ae361854942b734229665798"
    end
  end

  on_linux do
    if Hardware::CPU.arm?
      url "https://github.com/zachlatta/tasks/releases/download/edge/tasks_edge-SNAPSHOT-c09857c_linux_arm64.tar.gz"
      sha256 "0259f419d29f73fa6c082e84c65d1e79617aa7b7bf8d04a313b6a6773c27524a"
    else
      url "https://github.com/zachlatta/tasks/releases/download/edge/tasks_edge-SNAPSHOT-c09857c_linux_amd64.tar.gz"
      sha256 "745802b732c37106ceda05ac824bd7036b0c435624c0db8dc60daed450fd614d"
    end
  end

  def install
    bin.install "tasks"
  end

  test do
    assert_equal "edge-SNAPSHOT-c09857c\n", shell_output("#{bin}/tasks version")
  end
end
