# typed: false
# frozen_string_literal: true

# Code generated by cmd/update-homebrew-formula. DO NOT EDIT.

# Tasks installs the tasks command-line binary.
class Tasks < Formula
  desc "PostgreSQL-backed task management with CLI, web, and MCP interfaces"
  homepage "https://github.com/zachlatta/tasks"
  version "0.0.0.14"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/zachlatta/tasks/releases/download/edge/tasks_edge-SNAPSHOT-480f8fa_darwin_arm64.tar.gz"
      sha256 "d87c66e17d2f1836b68dfde0386d2869feeee50b65ab8b0ae96b0b29e8692ce8"
    else
      url "https://github.com/zachlatta/tasks/releases/download/edge/tasks_edge-SNAPSHOT-480f8fa_darwin_amd64.tar.gz"
      sha256 "ec9cf6b94139055e49b1680333efba7515c89d899bd29e8c9740c0559b9a1d97"
    end
  end

  on_linux do
    if Hardware::CPU.arm?
      url "https://github.com/zachlatta/tasks/releases/download/edge/tasks_edge-SNAPSHOT-480f8fa_linux_arm64.tar.gz"
      sha256 "a3e9096892e7e812cf71636100e82f098375bacc41ec349237faa90a9ec9eef7"
    else
      url "https://github.com/zachlatta/tasks/releases/download/edge/tasks_edge-SNAPSHOT-480f8fa_linux_amd64.tar.gz"
      sha256 "333710523b70d7cd34e5bc53a467b6acf9e2d1d5431bb7dae27085aa963ea43b"
    end
  end

  def install
    bin.install "tasks"
  end

  test do
    assert_equal "edge-SNAPSHOT-480f8fa\n", shell_output("#{bin}/tasks version")
  end
end
