# typed: false
# frozen_string_literal: true

# Code generated by cmd/update-homebrew-formula. DO NOT EDIT.

# Tasks installs the tasks command-line binary.
class Tasks < Formula
  desc "PostgreSQL-backed task management with CLI, web, and MCP interfaces"
  homepage "https://github.com/zachlatta/tasks"
  version "0.0.0.16"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/zachlatta/tasks/releases/download/edge/tasks_edge-SNAPSHOT-f1cacac_darwin_arm64.tar.gz"
      sha256 "049686d0d2e599aa836f9f7909ccebb733bc1fde1949261a3465aa7a9406033a"
    else
      url "https://github.com/zachlatta/tasks/releases/download/edge/tasks_edge-SNAPSHOT-f1cacac_darwin_amd64.tar.gz"
      sha256 "dd909f769f63a6d27bfcbd570fcc11210fca249cda7a7b7df743fa8e9dab373b"
    end
  end

  on_linux do
    if Hardware::CPU.arm?
      url "https://github.com/zachlatta/tasks/releases/download/edge/tasks_edge-SNAPSHOT-f1cacac_linux_arm64.tar.gz"
      sha256 "b87f6c6bf713615b041b21fc64cfaa0a80e75c3b416bcc41d1ef3cd9f8461c81"
    else
      url "https://github.com/zachlatta/tasks/releases/download/edge/tasks_edge-SNAPSHOT-f1cacac_linux_amd64.tar.gz"
      sha256 "b903df4bb839b6aa7fbe8619e3a05073a6960363f565e530f462ee138c97df7d"
    end
  end

  def install
    bin.install "tasks"
  end

  test do
    assert_equal "edge-SNAPSHOT-f1cacac\n", shell_output("#{bin}/tasks version")
  end
end
