# typed: false
# frozen_string_literal: true

# Code generated by cmd/update-homebrew-formula. DO NOT EDIT.

# TaskTracker installs the task-tracker command-line binary.
class TaskTracker < Formula
  desc "PostgreSQL-backed task tracker with CLI, web, and MCP interfaces"
  homepage "https://github.com/zachlatta/task-tracker"
  version "0.0.0.8"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/zachlatta/task-tracker/releases/download/edge/task-tracker_edge-SNAPSHOT-903cfc5_darwin_arm64.tar.gz"
      sha256 "b454d8fd81a0507753e27caf37a557a38e906e51ccfae8c1529374e13e95eff5"
    else
      url "https://github.com/zachlatta/task-tracker/releases/download/edge/task-tracker_edge-SNAPSHOT-903cfc5_darwin_amd64.tar.gz"
      sha256 "9d3eeef76265427e86dcd97709087427d1853afe531b7f09cfdff96895cefc48"
    end
  end

  on_linux do
    if Hardware::CPU.arm?
      url "https://github.com/zachlatta/task-tracker/releases/download/edge/task-tracker_edge-SNAPSHOT-903cfc5_linux_arm64.tar.gz"
      sha256 "4791dae700856960b54b73592a787244eb0ede8a3a396bcac3baf34ab7ca7552"
    else
      url "https://github.com/zachlatta/task-tracker/releases/download/edge/task-tracker_edge-SNAPSHOT-903cfc5_linux_amd64.tar.gz"
      sha256 "a4d5fc67d028cdc26948c1d0415961ff9f0d55b7bcd657a0c481361c70f1867a"
    end
  end

  def install
    bin.install "task-tracker"
  end

  test do
    assert_equal "edge-SNAPSHOT-903cfc5\n", shell_output("#{bin}/task-tracker version")
  end
end
