package main

import (
	"bufio"
	"bytes"
	"fmt"
	"io"
	"os"
	"path/filepath"
	"regexp"
	"strings"
	"text/template"
)

var (
	repositoryPattern = regexp.MustCompile(`^[A-Za-z0-9_.-]+/[A-Za-z0-9_.-]+$`)
	versionPattern    = regexp.MustCompile(`^[A-Za-z0-9][A-Za-z0-9.+_-]*$`)
	checksumPattern   = regexp.MustCompile(`^[0-9a-f]{64}$`)
)

type archive struct {
	Name   string
	SHA256 string
}

type formulaData struct {
	FormulaVersion string
	ReleaseVersion string
	Homepage       string
	AssetPrefix    string
	DarwinAMD64    archive
	DarwinARM64    archive
	LinuxAMD64     archive
	LinuxARM64     archive
}

const formulaTemplate = `# typed: false
# frozen_string_literal: true

# Code generated by cmd/update-homebrew-formula. DO NOT EDIT.

# Tasks installs the tasks command-line binary.
class Tasks < Formula
  desc "PostgreSQL-backed task management with CLI, web, and MCP interfaces"
  homepage "{{ .Homepage }}"
  version "{{ .FormulaVersion }}"

  on_macos do
    if Hardware::CPU.arm?
      url "{{ .AssetPrefix }}/{{ .DarwinARM64.Name }}"
      sha256 "{{ .DarwinARM64.SHA256 }}"
    else
      url "{{ .AssetPrefix }}/{{ .DarwinAMD64.Name }}"
      sha256 "{{ .DarwinAMD64.SHA256 }}"
    end
  end

  on_linux do
    if Hardware::CPU.arm?
      url "{{ .AssetPrefix }}/{{ .LinuxARM64.Name }}"
      sha256 "{{ .LinuxARM64.SHA256 }}"
    else
      url "{{ .AssetPrefix }}/{{ .LinuxAMD64.Name }}"
      sha256 "{{ .LinuxAMD64.SHA256 }}"
    end
  end

  def install
    bin.install "tasks"
  end

  test do
    assert_equal "{{ .ReleaseVersion }}\n", shell_output("#{bin}/tasks version")
  end
end
`

func main() {
	if len(os.Args) != 6 {
		fmt.Fprintln(os.Stderr, "usage: update-homebrew-formula <owner/repository> <formula-version> <release-version> <checksums> <output>")
		os.Exit(2)
	}

	checksums, err := os.Open(os.Args[4])
	if err != nil {
		fmt.Fprintf(os.Stderr, "open checksums: %v\n", err)
		os.Exit(1)
	}
	defer checksums.Close()

	formula, err := renderFormula(os.Args[1], os.Args[2], os.Args[3], checksums)
	if err != nil {
		fmt.Fprintf(os.Stderr, "render formula: %v\n", err)
		os.Exit(1)
	}
	if err := os.MkdirAll(filepath.Dir(os.Args[5]), 0o755); err != nil {
		fmt.Fprintf(os.Stderr, "create output directory: %v\n", err)
		os.Exit(1)
	}
	if err := os.WriteFile(os.Args[5], []byte(formula), 0o644); err != nil {
		fmt.Fprintf(os.Stderr, "write formula: %v\n", err)
		os.Exit(1)
	}
}

func renderFormula(repository, formulaVersion, releaseVersion string, checksums io.Reader) (string, error) {
	if !repositoryPattern.MatchString(repository) {
		return "", fmt.Errorf("invalid repository %q", repository)
	}
	if !versionPattern.MatchString(formulaVersion) {
		return "", fmt.Errorf("invalid formula version %q", formulaVersion)
	}
	if !versionPattern.MatchString(releaseVersion) {
		return "", fmt.Errorf("invalid release version %q", releaseVersion)
	}

	archives := make(map[string]archive)
	scanner := bufio.NewScanner(checksums)
	for scanner.Scan() {
		fields := strings.Fields(scanner.Text())
		if len(fields) != 2 || !checksumPattern.MatchString(fields[0]) || filepath.Base(fields[1]) != fields[1] {
			return "", fmt.Errorf("invalid checksum line %q", scanner.Text())
		}
		for _, platform := range []string{"darwin_amd64", "darwin_arm64", "linux_amd64", "linux_arm64"} {
			if strings.HasSuffix(fields[1], "_"+platform+".tar.gz") {
				if _, exists := archives[platform]; exists {
					return "", fmt.Errorf("multiple archives for %s", platform)
				}
				archives[platform] = archive{Name: fields[1], SHA256: fields[0]}
			}
		}
	}
	if err := scanner.Err(); err != nil {
		return "", fmt.Errorf("read checksums: %w", err)
	}
	for _, platform := range []string{"darwin_amd64", "darwin_arm64", "linux_amd64", "linux_arm64"} {
		if _, exists := archives[platform]; !exists {
			return "", fmt.Errorf("missing %s archive", platform)
		}
	}

	data := formulaData{
		FormulaVersion: formulaVersion,
		ReleaseVersion: releaseVersion,
		Homepage:       "https://github.com/" + repository,
		AssetPrefix:    "https://github.com/" + repository + "/releases/download/edge",
		DarwinAMD64:    archives["darwin_amd64"],
		DarwinARM64:    archives["darwin_arm64"],
		LinuxAMD64:     archives["linux_amd64"],
		LinuxARM64:     archives["linux_arm64"],
	}
	tmpl, err := template.New("formula").Parse(formulaTemplate)
	if err != nil {
		return "", fmt.Errorf("parse template: %w", err)
	}
	var output bytes.Buffer
	if err := tmpl.Execute(&output, data); err != nil {
		return "", fmt.Errorf("execute template: %w", err)
	}
	return output.String(), nil
}
